#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 20, 2017 05:44:31 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    global che46
    che46 = StringVar()
    global che47
    che47 = StringVar()
    global che48
    che48 = StringVar()
    global che49
    che49 = StringVar()
    global che51
    che51 = StringVar()
    global che52
    che52 = StringVar()
    global che53
    che53 = StringVar()
    global che54
    che54 = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ChathurBot
    ChathurBot.vp_start_gui()


